### ISSUE TITLE
Backend crashes on start

### ISSUE THREAD

**Issue by Neelzee** [Unrated-Limited-Unlimited/ua-backend#18]
The newest changes in `dev` which only tested against a `H2`-db, break when using `PostgreSQL`-db.

How to test using docker:
```bash
docker pull postgres:latest
```
```bash
docker run --name postgres_db -e POSTGRES_DB=ulu_prod -e POSTGRES_USER=ulu_backend -e POSTGRES_PASSWORD=pswd123 -p 5432:5432 -d postgres
```

And change the url in `application.yml`:

```yml
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/ulu_prod
```
